### ISSUE TITLE
CALF GCN assertion error while processing

### ISSUE THREAD

**Issue by gorayni** [SilvioGiancola/SoccerNetv2-DevKit#13]
I tried to train the CALF GCN model with the following command line:

```
python src/main.py --SoccerNet_path=/datasets/soccernet \
                               --features=ResNET_TF2_PCA512.npy \
                               --num_features=512 \
                               --model_name=calib_GCN \
                               --batch_size 32 \
                               --evaluation_frequency 20 \
                               --chunks_per_epoch 18000 \
                               --model_name=calib_GCN_run_${i}  \
                               --backbone_feature=2DConv \
                               --backbone_player=resGCN-14 \
                               --dist_graph_player=25 \
                               --feature_multiplier 2 \
                               --class_split visual
```
This line is basically the same as the one from the README.md file [here](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Task1-ActionSpotting/CALF_Calibration_GCN), but without the **calibration** option. The result I get from running it is the following:

```
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]  Starting main function
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]  Parameters:
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]   SoccerNet_path : /datasets/soccernet
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]         features : ResNET_TF2_PCA512.npy
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]       max_epochs : 1000
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]     load_weights : None
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]       model_name : calib_GCN_run_
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]             mode : 0
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]        test_only : False
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]        challenge : False
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]          teacher : False
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]             tiny : None
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]      class_split : visual
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]         K_params : None
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]     num_features : 512
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]  chunks_per_epoch : 18000
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]  evaluation_frequency : 20
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]      dim_capsule : 16
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]        framerate : 2
2021-07-12 16:32:33,120 [MainThread  ] [INFO ]       chunk_size : 120
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  receptive_field : 40
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]     lambda_coord : 5.0
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]     lambda_noobj : 0.5
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  loss_weight_segmentation : 0.000367
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  loss_weight_detection : 1.0
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]   num_detections : 15
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  feature_multiplier : 2
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  backbone_player : resGCN-14
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  backbone_feature : 2DConv
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]      calibration : False
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  calibration_field : False
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  calibration_cone : False
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  calibration_confidence : False
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  dim_representation_w : 64
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  dim_representation_h : 32
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  dim_representation_c : 3
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  dim_representation_player : 2
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]  dist_graph_player : 25
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]     with_dropout : 0.0
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]       batch_size : 32
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]               LR : 0.001
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]         patience : 25
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]              GPU : -1
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]   max_num_worker : 4
2021-07-12 16:32:33,121 [MainThread  ] [INFO ]         loglevel : INFO
2021-07-12 16:32:33,255 [MainThread  ] [INFO ]  Checking/Download features and labels locally
2021-07-12 16:32:35,530 [MainThread  ] [INFO ]  Pre-compute clips
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [08:38<00:00,  1.73s/it]
2021-07-12 16:41:13,821 [MainThread  ] [INFO ]  Checking/Download features and labels locally
2021-07-12 16:41:19,122 [MainThread  ] [INFO ]  Pre-compute clips
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [05:06<00:00,  3.06s/it]
2021-07-12 16:46:25,305 [MainThread  ] [INFO ]  Checking/Download features and labels locally
2021-07-12 16:46:25,808 [MainThread  ] [INFO ]  Checking/Download features and labels locally
2021-07-12 16:46:28,088 [MainThread  ] [INFO ]  ContextAwareModel(
  (conv_1): Conv2d(1, 128, kernel_size=(1, 512), stride=(1, 1))
  (conv_2): Conv2d(128, 32, kernel_size=(1, 1), stride=(1, 1))
  (pad_p_1): ZeroPad2d(padding=(0, 0, 5, 6), value=0.0)
  (pad_p_2): ZeroPad2d(padding=(0, 0, 13, 13), value=0.0)
  (pad_p_3): ZeroPad2d(padding=(0, 0, 19, 20), value=0.0)
  (pad_p_4): ZeroPad2d(padding=(0, 0, 39, 40), value=0.0)
  (conv_p_1): Conv2d(32, 8, kernel_size=(12, 1), stride=(1, 1))
  (conv_p_2): Conv2d(32, 16, kernel_size=(27, 1), stride=(1, 1))
  (conv_p_3): Conv2d(32, 32, kernel_size=(40, 1), stride=(1, 1))
  (conv_p_4): Conv2d(32, 64, kernel_size=(80, 1), stride=(1, 1))
  (node_encoder): Linear(in_features=8, out_features=64, bias=True)
  (edge_encoder): Linear(in_features=8, out_features=64, bias=True)
  (layers): ModuleList(
    (0): DeepGCNLayer(block=res)
    (1): DeepGCNLayer(block=res)
    (2): DeepGCNLayer(block=res)
    (3): DeepGCNLayer(block=res)
    (4): DeepGCNLayer(block=res)
    (5): DeepGCNLayer(block=res)
    (6): DeepGCNLayer(block=res)
    (7): DeepGCNLayer(block=res)
    (8): DeepGCNLayer(block=res)
    (9): DeepGCNLayer(block=res)
    (10): DeepGCNLayer(block=res)
    (11): DeepGCNLayer(block=res)
    (12): DeepGCNLayer(block=res)
    (13): DeepGCNLayer(block=res)
  )
  (lin): Linear(in_features=64, out_features=152, bias=True)
  (pad_seg): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
  (conv_seg): Conv2d(304, 128, kernel_size=(3, 1), stride=(1, 1))
  (batch_seg): BatchNorm2d(240, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
  (max_pool_spot): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
  (pad_spot_1): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
  (conv_spot_1): Conv2d(136, 32, kernel_size=(3, 1), stride=(1, 1))
  (max_pool_spot_1): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
  (pad_spot_2): ZeroPad2d(padding=(0, 0, 1, 1), value=0.0)
  (conv_spot_2): Conv2d(32, 16, kernel_size=(3, 1), stride=(1, 1))
  (max_pool_spot_2): MaxPool2d(kernel_size=(3, 1), stride=(2, 1), padding=0, dilation=1, ceil_mode=False)
  (conv_conf): Conv2d(464, 30, kernel_size=(1, 1), stride=(1, 1))
  (conv_class): Conv2d(464, 120, kernel_size=(1, 1), stride=(1, 1))
  (softmax): Softmax(dim=-1)
)
2021-07-12 16:46:28,089 [MainThread  ] [INFO ]  Total number of parameters: 741828
2021-07-12 16:46:28,090 [MainThread  ] [INFO ]  start training
  0%|                                                                                                                                   | 0/563 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "src/main.py", line 213, in <module>
    main(args)
  File "src/main.py", line 82, in main
    trainer(train_loader, val_loader, val_metric_loader, test_loader,
  File "/code/soccerNetv2-devkit/Task1-ActionSpotting/CALF_Calibration_GCN/src/train.py", line 36, in trainer
    loss_training = train(
  File "/code/soccerNetv2-devkit/Task1-ActionSpotting/CALF_Calibration_GCN/src/train.py", line 150, in train
    output_segmentation, output_spotting = model(feats, representations)
  File "/home/gorayni/anaconda3/envs/CALF-pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/soccerNetv2-devkit/Task1-ActionSpotting/CALF_Calibration_GCN/src/model.py", line 127, in forward
    r_concatenation = self.forward_GCN(inputs, representation_inputs)
  File "/code/soccerNetv2-devkit/Task1-ActionSpotting/CALF_Calibration_GCN/src/model.py", line 476, in forward_GCN
    x = self.layers[0].conv(x, edge_index)
  File "/home/gorayni/anaconda3/envs/CALF-pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gorayni/anaconda3/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/nn/conv/gen_conv.py", line 152, in forward
    out = self.propagate(edge_index, x=x, edge_attr=edge_attr, size=size)
  File "/home/gorayni/anaconda3/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 216, in propagate
    size = self.__check_input__(edge_index, size)
  File "/home/gorayni/anaconda3/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 91, in __check_input__
    assert edge_index.dim() == 2
AssertionError

```

**Comment by SilvioGiancola** [comment]
Hi @gorayni,

Thank you for raising this issue. The error thrown by the code is due to the lack of edges in the graph representation. If the bounding boxes are not projected in the field (without `--calibration`) there is no "metric" distance we could use to filter the "close" players. 

In particular, I am referring to those blocks that look for all neighboring players within a metric distance, defining the edges:
 - https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/b14aa2f5923a11803139c5cc329b46d44645453f/Task1-ActionSpotting/CALF_Calibration_GCN/src/dataset.py#L332
 - https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/b14aa2f5923a11803139c5cc329b46d44645453f/Task1-ActionSpotting/CALF_Calibration_GCN/src/dataset.py#L419
 - https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/b14aa2f5923a11803139c5cc329b46d44645453f/Task1-ActionSpotting/CALF_Calibration_GCN/src/dataset.py#L828
 - https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/b14aa2f5923a11803139c5cc329b46d44645453f/Task1-ActionSpotting/CALF_Calibration_GCN/src/dataset.py#L913

I see 3 solutions that could fix your problem:
1. Create dummy edges linking to the player to itself. You can simply add `Edges.append([i_box, i_box])` before the for loops.
2. Linking all players between each other. You can simply remove the condition `dist < self.max_dist_player:` in an else statement after the `if self.args.calibration:`.
3. Figuring out a new way to find the closest players in the pixel space.

I tried the 1st solution and it does not throw me any error. Let me know if that works for you as well.

Best,
