### ISSUE TITLE
Download SoccerNet Dataset using API - HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Wilann** [SilvioGiancola/SoccerNetv2-DevKit#22]
Hi again SoccerNet Team, thank you so much for providing the dataset for download! It'll help lots with my learning process. That being said, I'm having an issue with downloading the dataset using the API.

I'm running the script from `./Download` as:
`python DownloadSoccerNet.py`

I've edited `DownloadSoccerNet.py` to download all relevant data (as far as I know of) as:
```
import SoccerNet
from SoccerNet.Downloader import SoccerNetDownloader

mySoccerNetDownloader = SoccerNetDownloader(LocalDirectory="./Videos")
mySoccerNetDownloader.password = input("Password for Videos?\n")

# Download SoccerNet labels
mySoccerNetDownloader.downloadGames(files=["Labels.json"], split=["train","valid","test"]) # download labels
mySoccerNetDownloader.downloadGames(files=["Labels-v2.json"], split=["train","valid","test"]) # download labels SN v2
mySoccerNetDownloader.downloadGames(files=["Labels-cameras.json"], split=["train","valid","test"]) # download labels for camera shot
mySoccerNetDownloader.downloadGames(files=["Labels-replays.json"], split=["train","valid","test"])

# Download SoccerNet features
mySoccerNetDownloader.downloadGames(files=["1_ResNET_TF2.npy", "2_ResNET_TF2.npy"], split=["train","valid","test"]) # download Features
mySoccerNetDownloader.downloadGames(files=["1_ResNET_TF2_PCA512.npy", "2_ResNET_TF2_PCA512.npy"], split=["train","valid","test"]) # download Features reduced with PCA
mySoccerNetDownloader.downloadGames(files=["1_player_boundingbox_maskrcnn.json", "2_player_boundingbox_maskrcnn.json"], split=["train","valid","test"]) # download Player Bounding Boxes inferred with MaskRCNN
mySoccerNetDownloader.downloadGames(files=["1_field_calibration_ccbv.json", "2_field_calibration_ccbv.json"], split=["train","valid","test"]) # download Field Calibration inferred with CCBV

mySoccerNetDownloader.downloadGames(files=["1.mkv", "2.mkv"], split=["train","valid","test"]) # download LQ Videos
mySoccerNetDownloader.downloadGames(files=["1_HQ.mkv", "2_HQ.mkv", "video.ini"], split=["train","valid","test"]) # download HQ Videos

```

After getting the password from signing the NDA and entering it, it started downloading as expected. Since I kept my PC on for 2 days and had accumulated 320 GB of the dataset (I didn't expect over 320 GB!), I decided to give it a break. Once turning it back on and running the script again, I get this output: 
```
./Videos/england_epl/2014-2015/2015-02-21 - 18-00 Chelsea 1 - 1 Burnley/Labels.json already exists
./Videos/england_epl/2014-2015/2015-02-21 - 18-00 Crystal Palace 1 - 2 Arsenal/Labels.json already exists
./Videos/england_epl/2014-2015/2015-02-21 - 18-00 Swansea 2 - 1 Manchester United/Labels.json already exists
./Videos/england_epl/2014-2015/2015-02-22 - 19-15 Southampton 0 - 2 Liverpool/Labels.json already exists
./Videos/england_epl/2015-2016/2015-08-08 - 19-30 Chelsea 2 - 2 Swansea/Labels.json already exists
./Videos/england_epl/2015-2016/2015-08-29 - 17-00 Chelsea 1 - 2 Crystal Palace/Labels.json already exists
...
./Videos/spain_laliga/2016-2017/2017-03-12 - 22-45 Real Madrid 2 - 1 Betis/Labels-cameras.json already exists
./Videos/spain_laliga/2016-2017/2017-04-02 - 17-15 Real Madrid 3 - 0 Alaves/Labels-cameras.json already exists
./Videos/spain_laliga/2016-2017/2017-04-08 - 21-45 Malaga 2 - 0 Barcelona/Labels-cameras.json already exists
./Videos/spain_laliga/2016-2017/2017-04-26 - 20-30 Barcelona 7 - 1 Osasuna/Labels-cameras.json already exists
HTTP Error 404: Not Found
HTTP Error 404: Not Found
```
After which there's no more output, but the script isn't finished running. 

I'd be grateful if anyone could look into this bug for me so I can complete the download, possibly let me know how big the dataset is, and if I've missed anything I may also want to download. 
Cheers! Thank you so much for reading this issue.

**Comment by Wilann** [comment]
Update: 

After a lot more `HTTP Error 404: Not Found`s and waiting ~30 mins, I got error:
```
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/site-packages/SoccerNet/Downloader.py", line 60, in downloadFile
    urllib.request.urlretrieve(
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DownloadSoccerNet.py", line 15, in <module>
    mySoccerNetDownloader.downloadGames(files=["Labels-replays.json"], split=["train","valid","test"])
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/site-packages/SoccerNet/Downloader.py", line 210, in downloadGames
    self.downloadGame(game=game, files=files, verbose=verbose)
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/site-packages/SoccerNet/Downloader.py", line 184, in downloadGame
    res = self.downloadFile(path_local=os.path.join(GameDirectory, file),
  File "/home/wilsonchan/anaconda3/envs/annotation/lib/python3.8/site-packages/SoccerNet/Downloader.py", line 67, in downloadFile
    os.remove(path_local)
FileNotFoundError: [Errno 2] No such file or directory: './Videos/germany_bundesliga/2014-2015/2015-02-21 - 17-30 Paderborn 0 - 6 Bayern Munich/Labels-replays.json'
```

Checking `'./Videos/germany_bundesliga/2014-2015/2015-02-21 - 17-30 Paderborn 0 - 6 Bayern Munich/Labels-replays.json'` myself, it's true that this file doesn't exist on my machine, but I'm not sure why that matters since I'm trying to download it.

**Comment by SilvioGiancola** [comment]
Hi @Wilann ,

Thank you for raising that issue. 

As far as I remember, you do not need the "Labels-replays.json" for the train/valid/test sets, as they are redundant with "Labels-cameras.json". We provided "Labels-replays.json" for the challenge set only, to give the minimal camera information that will allow anyone to infer on the challenge set. Maybe @meisamjam or @jagob could confirm?

To solve your issue, you can simply not consider this command line. Also, note that 
`mySoccerNetDownloader.downloadGames(files=["1_field_calibration_ccbv.json", "2_field_calibration_ccbv.json"], split=["train","valid","test"]) # download Field Calibration inferred with CCBV`
should be 
`mySoccerNetDownloader.downloadGames(files=["1_field_calib_ccbv.json", "2_field_calib_ccbv.json"], split=["train","valid","test"]) # download Field Calibration inferred with CCBV`
as describe in https://github.com/SilvioGiancola/SoccerNetv2-DevKit/issues/16.

Let us know if you are still facing issues

**Comment by Wilann** [comment]
Hi @SilvioGiancola, thank you for your reply - it worked! 

For anyone reading this in the future, I removed the download line for `Labels-replays.json` and changed the Field Calibration file names.
