### ISSUE TITLE
Feature Extraction for Custom Video - GPU not compatible? 

### ISSUE THREAD

**Issue by Wilann** [SilvioGiancola/SoccerNetv2-DevKit#26]
Hi again, 

I'm testing the feature extraction function on my custom video. From the root, I'm running: 
```
python Features/VideoFeatureExtractor.py \
--path_video 'Download/BWF TV (Copy)/20210317-20210321 YONEX All England Open Badminton Championships 2021/20210319 - YONEX All England Open 2021 _ Day 3 - Kento Momota (JPN) [1] vs Lee Zii Jia (MAS) [6].mp4' \ 
--path_features='Download/BWF TV (Copy)/20210317-20210321 YONEX All England Open Badminton Championships 2021/features.npy' \
--PCA=Features/pca_512_TF2.pkl \
--PCA_scaler=Features/average_512_TF2.pkl
```

And getting quite a long error: 
```
2021-09-09 13:55:54.204894: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-09-09 13:55:55.004666: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-09-09 13:55:55.027734: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.028163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:0b:00.0 name: GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.68GiB deviceMemoryBandwidth: 871.81GiB/s
2021-09-09 13:55:55.028178: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-09-09 13:55:55.029177: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-09-09 13:55:55.030163: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-09-09 13:55:55.030307: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-09-09 13:55:55.031239: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-09-09 13:55:55.031700: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-09-09 13:55:55.033647: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-09-09 13:55:55.033742: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.034211: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.034623: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-09-09 13:55:55.034969: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-09 13:55:55.059732: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3393815000 Hz
2021-09-09 13:55:55.060647: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5563c9e3d200 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-09 13:55:55.060669: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-09-09 13:55:55.130591: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.131080: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5563c99bee50 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-09-09 13:55:55.131093: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 3090, Compute Capability 8.6
2021-09-09 13:55:55.131224: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.131729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:0b:00.0 name: GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.68GiB deviceMemoryBandwidth: 871.81GiB/s
2021-09-09 13:55:55.131750: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-09-09 13:55:55.131779: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-09-09 13:55:55.131790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-09-09 13:55:55.131799: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-09-09 13:55:55.131807: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-09-09 13:55:55.131814: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-09-09 13:55:55.131823: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-09-09 13:55:55.131868: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.132376: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-09 13:55:55.132841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-09-09 13:55:55.132860: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
```

After the Terminal hanging for a few minutes, I get: 
```
Traceback (most recent call last):
  File "Features/VideoFeatureExtractor.py", line 200, in <module>
    FPS=args.FPS)
  File "Features/VideoFeatureExtractor.py", line 66, in __init__
    classes=1000)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/applications/resnet.py", line 517, in ResNet152
    input_tensor, input_shape, pooling, classes, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/applications/resnet.py", line 171, in ResNet
    x = layers.Conv2D(64, 7, strides=2, use_bias=use_bias, name='conv1_conv')(x)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 204, in build
    dtype=self.dtype)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 614, in add_weight
    caching_device=caching_device)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 750, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2597, in default_variable_creator
    shape=shape)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1518, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1651, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/keras/initializers/initializers_v2.py", line 397, in __call__
    return super(VarianceScaling, self).__call__(shape, dtype=_get_dtype(dtype))
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py", line 561, in __call__
    return self._random_generator.random_uniform(shape, -limit, limit, dtype)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py", line 1044, in random_uniform
    shape=shape, minval=minval, maxval=maxval, dtype=dtype, seed=self.seed)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py", line 288, in random_uniform
    shape = tensor_util.shape_tensor(shape)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 1029, in shape_tensor
    return ops.convert_to_tensor(shape, dtype=dtype, name="shape")
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 97, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "/home/wilsonchan/anaconda3/envs/SoccerNet-FeatureExtraction/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 539, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid

```

I'm using an RTX 3090, and it seems it isn't compatible. It seems I need to "rebuild TensorFlow with the appropriate compiler flags"? 

I tried re-installing TensorFlow with `pip install tensorflow` but nothing was updated. 

If you or your team has any leads on what the issue is I'd greatly appreciate it if you'd let me know! Thank you so much for reading this issue, again.

**Comment by Wilann** [comment]
Sorry, just realized this is a TensorFlow issue and not about SoccerNet. Apologies for opening the issue here!
